### ISSUE TITLE
Scoragami board not displaying

### ISSUE THREAD

**Issue by glutenfather** [ACMerriman/scorigami#27]
Pretty sure this has been happening for a few days now, but whenever I go to visit the page all I get is this:
![image](https://user-images.githubusercontent.com/66861536/121436550-9f6b6f80-c935-11eb-8f92-b1c573c0cac1.png)

No matter what inputs I do on the page, the board refuses to load.

**Comment by ACMerriman** [comment]
I'm aware of this issue and know what is causing it. Unfortunately it looks like this may be an issue with the server it is hosted on which I don't have much control over at the moment. Hopefully it will be fixed soon but in the meantime, here is what the chart looks like as of June 9, 2021.

![image](https://user-images.githubusercontent.com/9051751/121438010-427db280-c951-11eb-9df8-f5e6f79e381f.png)

**Comment by PlazmaCube** [comment]
I had the same issue. Currently it's saying the site under maintinence, meaning it's likely the site is likely being worked on by the host. In the next few days hopefully it will be back up.

In the meantime, I have the current NFL Scorigami Card Downloaded as well, this time with a Cool Shade of Purple because Purple is better than green.[
![Scorigami 2021 (Purple)](https://user-images.githubusercontent.com/73444947/121794096-3d2b9c80-cbcb-11eb-945f-cdb03e75c8aa.png)
](url)
