### ISSUE TITLE
Suggestion for this week's games

### ISSUE THREAD

**Issue by aztechunter** [ACMerriman/scorigami#32]
Instead of putting "No Scorigami" put the number of occurences. I.E. Lions-Bengals game on 2021/10/17 ended in a 34-11 score. This should show up as "2nd Occurrence" on the bottom.

**Comment by ACMerriman** [comment]
Due to the way the data is stored, I can't do "Xth occurrence", but I can display how many games have had that score to date. The difference is if two games have the same score within the same week, the former would show different numbers (ex: 4th and 5th occurrence) and the latter would show the same (ex: 5 occurrences).
